### ISSUE TITLE
apply label "synced" for issues that were syncronysed 

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/gh-jira-sync-bot#51]
Some teams do not want to have the comment on the tickets, since that leads to an internal ticket. We can offer a different functionality and apply "synced" label.

To reduce API load, it must be a prerequisite for user to have this Label created before. We can write a comment on the ticket if Label was requested but not added to the list

**Comment by lorenzo-medici** [comment]
Hi, I would like to take a shot at this.

**Comment by beliaev-maksim** [comment]
@lorenzo-medici please go

I think this also should be a configuration option for this

**Comment by lorenzo-medici** [comment]
Since the configuration is only applied through environment variables, it is currently impossible to change it for each test case.
I opened PR #58  to allow each test function to declare custom configuration of the environment variables, with cleanup at the end to let following tests proceed with the default test configuration found in `dumm_env`.
Please review it and give all the feedback you find necessary.

I also have a question about the feature: how does it interact with `add_gh_comment` if this is set? I think the most logical option is that we will both write the normal comment and add the Synced label.

**Comment by beliaev-maksim** [comment]
@lorenzo-medici that is not correct. 
you are talking about the defaults `DEFAULT_BOT_CONFIG`
however, the actual config comes from GitHub repo. For this, you need to tweak payloads: 
https://github.com/canonical/gh-jira-sync-bot/blob/15a70e99918ce59fb43b87f5270e58459edc9ae0/tests/unit/url_responses/auth_github_responses.yaml#L32


though, for your test we might need two separate payloads for two different cases

**Comment by lorenzo-medici** [comment]
Oh I see, I completely misunderstood the settings stuff. I will close the PR.

So for testing I should add a new file under `url_responses` that returns the config with the new fields, and an endpoint to check for an existing label, and then load it in the new test cases. As you said, it should be two files with one returning the label as existing, and the other one without it to check for all situations.
